---
title: "manova"
output: html_document
---

```{r}
# Load necessary packages
#install.packages("tidyverse")
library(tidyverse)
library(ggpubr)
library(rstatix)
library(car)
library(broom)
library(dplyr)
library(tidyr)
library(haven)
library(readxl)

# Read dataset
heart_failure <- read_excel("C:/Users/lenovo/Downloads/heart_failure_clinical_records.xlsx")
View(heart_failure)
```


```{r}
# Recode categorical variables
heart_failure$smoking<-factor(heart_failure$smoking)
heart_failure$anaemia<-factor(heart_failure$anaemia)
summary(heart_failure)

```
```{r}
# Group size by smoking status
heart_failure %>%
  group_by(smoking) %>%
  dplyr::summarise(N = n())
```
```{r}
# Group means and standard deviations by smoking
#smoking duzeyleri bazında degisken ortalamaları ve sapmalar
heart_failure %>% 
  group_by(smoking) %>%
  summarise(across(-anaemia, list(mean=mean,sd=sd)))
```

```{r}
# Group means and standard deviations by anaemia
heart_failure %>% 
  group_by(anaemia) %>%
  summarise(across(-smoking, list(mean=mean,sd=sd)))
```

```{r}
# Mean plots by smoking
library(gplots)
#smoking için
plotmeans(serum_creatinine~smoking,xlab="smoking",ylab="serum_creatinine", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(sex~smoking, xlab="smoking",ylab="sex", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(age~smoking,xlab="smoking",ylab="age", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(creatinine_phosphokinase~smoking, xlab="smoking",ylab="cratinine_phosphokirase", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(ejection_fraction~smoking, xlab="smoking",ylab="ejection_fraction", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(diabetes~smoking,xlab="smoking",ylab="diabetes", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(platelets~smoking, xlab="smoking",ylab="platelets", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(serum_sodium~smoking, xlab="smoking",ylab="serum_sodium", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(time~smoking,xlab="smoking",ylab="time", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(death_event~smoking, xlab="smoking",ylab="death_event", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(high_blood_pressure~smoking, xlab="smoking",ylab="high_blood_pressure", main="Mean Plot\nwith 95% CI",data=heart_failure)
```

```{r}
# Mean plots by anaemia
library(gplots)
#yüksek tansiyon için
plotmeans(serum_creatinine~anaemia,xlab="anaemia",ylab="serum_creatinine", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(sex~anaemia, xlab="anaemia",ylab="sex", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(age~anaemia,xlab="anaemia",ylab="age", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(creatinine_phosphokinase~anaemia, xlab="anaemia",ylab="cratinine_phosphokirase", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(ejection_fraction~anaemia, xlab="anaemia",ylab="ejection_fraction", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(diabetes~anaemia,xlab="anaemia",ylab="diabetes", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(platelets~anaemia, xlab="anaemia",ylab="platelets", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(serum_sodium~anaemia, xlab="anaemia",ylab="serum_sodium", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(time~anaemia,xlab="anaemia",ylab="time", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(death_event~anaemia, xlab="anaemia",ylab="death_event", main="Mean Plot\nwith 95% CI",data=heart_failure)

plotmeans(high_blood_pressure~anaemia, xlab="anaemia",ylab="high_blood_pressure", main="Mean Plot\nwith 95% CI",data=heart_failure)
```

```{r}
# Multivariate normality test
library(dplyr)
heart_failure %>%
  dplyr::select(serum_sodium,platelets,ejection_fraction,serum_creatinine,creatinine_phosphokinase,time,age) %>%
  mshapiro_test()
```
```{r}
# Box's M test for homogeneity of covariance matrices
#install.packages("biotools")
library(biotools)
box_m(heart_failure[, c("serum_sodium","ejection_fraction","serum_creatinine","time","age")],heart_failure$smoking)

```
```{r}
# MANOVA - Multivariate test for smoking
heart_manova <- manova(cbind(serum_sodium,ejection_fraction,serum_creatinine,time,age) ~ smoking,data=heart_failure)

summary(heart_manova, test = "Hotelling-Lawley")

summary(heart_manova, test = "Wilks")

summary(heart_manova, test = "Pillai")

summary(heart_manova, test = "Roy")
```

```{r}
# Levene's test for homogeneity of variances
library(car)
heart_failure %>% 
  pivot_longer( c(serum_sodium,ejection_fraction,serum_creatinine,time,age),names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  levene_test(value ~ smoking,center=mean)
```

```{r}
# Between-subject effects: Which variable is driving the difference?
summary.aov(heart_manova)
```

```{r}
# Tukey post-hoc comparisons
m_tukey <- heart_failure%>%
  pivot_longer( c(serum_sodium,ejection_fraction,serum_creatinine,time,age),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  tukey_hsd(value ~ smoking)
m_tukey<-m_tukey[,c(1,2,4,3,5:9)]
m_tukey
```

```{r}
# Two-way MANOVA (interaction of smoking and anaemia)
library(heplots)
boxM( cbind(serum_sodium,ejection_fraction,serum_creatinine,time,age,creatinine_phosphokinase) ~ smoking*anaemia, data=heart_failure)
```

```{r}
#MANOVA  
smoking_cift <- manova(cbind(serum_sodium,ejection_fraction,serum_creatinine,time,age,creatinine_phosphokinase) ~ smoking*anaemia,data=heart_failure)
summary(smoking_cift, test = "Wilks")
```

```{r}
# Levene’s test for interaction
#install.packages("car")
library(car)
heart_failure %>% 
  pivot_longer( c(serum_sodium,age,platelets),names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  levene_test(value ~ smoking*anaemia,center=mean)
```

```{r}
# Between-subject effects: Which variable is significant in interaction?
summary.aov(smoking_cift)
```
```{r}
# Multiple comparisons for anaemia
m_tukey2 <- heart_failure %>%
  pivot_longer( c(platelets,serum_sodium,creatinine_phosphokinase),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  tukey_hsd(value ~ anaemia*smoking)
m_tukey2<-m_tukey2[,c(1,2,4,3,5:9)]
anaemia_etk<-filter(m_tukey2, term=="anaemia")
anaemia_etk
```

```{r}
# Interaction plots for smoking and anaemia
attach(heart_failure)
interaction.plot(anaemia,smoking,serum_sodium, fun=mean, type="l", legend=TRUE,col=1:3, lwd=2)
interaction.plot(anaemia,smoking,platelets, fun=mean, type="l", legend=TRUE, col=1:3,lwd=2)
detach(heart_failure)


```


